name: practical1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - pip=23.0.1
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - pip:
    - pytorch-lightning==2.0.1
    - tqdm==4.65.0
    - datasets==2.11.0
    - torchtext==0.15.1
    - tensorboard==2.11.0
    - spacy
    - tensorboard
    - ruff
    - scikit-learn